In [0]:
# Transformation is when assigning a value to a variable which based on RDD it will create a copy of the original file where the original file #is imutable but the copy of the file is mutable.

# Action on the other hand is when we execute an operation on the record and it will take few time to execute the command

# Note: The above data are built in dataset

# Data in right menue help us to add data to the database
# Dataset can be add but should be enable first [Setting -> Admin Console -> Workspace Setting -> DBFS File Browser: (set to enable)]
    # Note: Referesh page to take effect

# Data if you now check data menue you will see two tab now 'Database Tables' and 'DBFS'

# To upload dataset in databricks within Notebook click [ file -> upload; upload dataset; copy the path from opened window

# Download dataset from www.kaggle.com

In [0]:
spark

In [0]:
dbutils.help()

In [0]:
dbutils.fs.ls("dbfs:/")

[FileInfo(path='dbfs:/Volume/', name='Volume/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/Volumes/', name='Volumes/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/databricks-datasets/', name='databricks-datasets/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/databricks-results/', name='databricks-results/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/tmp/', name='tmp/', size=0, modificationTime=1713121216283),
 FileInfo(path='dbfs:/volume/', name='volume/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/volumes/', name='volumes/', size=0, modificationTime=0)]

In [0]:
dbutils.fs.ls("/databricks-datasets")

[FileInfo(path='dbfs:/databricks-datasets/COVID/', name='COVID/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/README.md', name='README.md', size=976, modificationTime=1532502324000),
 FileInfo(path='dbfs:/databricks-datasets/Rdatasets/', name='Rdatasets/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/SPARK_README.md', name='SPARK_README.md', size=3359, modificationTime=1455505834000),
 FileInfo(path='dbfs:/databricks-datasets/adult/', name='adult/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/airlines/', name='airlines/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/amazon/', name='amazon/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/asa/', name='asa/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/atlas_higgs/', name='atlas_higgs/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/bikeSharing/', name='bikeSharing/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/cctvVideos/', name='cctvVideos/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/credit-card-fraud/', name='credit-card-fraud/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/cs100/', name='cs100/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/cs110x/', name='cs110x/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/cs190/', name='cs190/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/data.gov/', name='data.gov/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/definitive-guide/', name='definitive-guide/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/delta-sharing/', name='delta-sharing/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/flights/', name='flights/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/flower_photos/', name='flower_photos/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/flowers/', name='flowers/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/genomics/', name='genomics/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/hail/', name='hail/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/identifying-campaign-effectiveness/', name='identifying-campaign-effectiveness/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/iot/', name='iot/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/iot-stream/', name='iot-stream/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/learning-spark/', name='learning-spark/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/learning-spark-v2/', name='learning-spark-v2/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/lending-club-loan-stats/', name='lending-club-loan-stats/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/med-images/', name='med-images/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/media/', name='media/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/mnist-digits/', name='mnist-digits/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/news20.binary/', name='news20.binary/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/nyctaxi/', name='nyctaxi/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/nyctaxi-with-zipcodes/', name='nyctaxi-with-zipcodes/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/online_retail/', name='online_retail/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/overlap-join/', name='overlap-join/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/power-plant/', name='power-plant/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/retail-org/', name='retail-org/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/rwe/', name='rwe/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/sai-summit-2019-sf/', name='sai-summit-2019-sf/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/sample_logs/', name='sample_logs/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/samples/', name='samples/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/sfo_customer_survey/', name='sfo_customer_survey/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/sms_spam_collection/', name='sms_spam_collection/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/songs/', name='songs/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/structured-streaming/', name='structured-streaming/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/timeseries/', name='timeseries/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/tpch/', name='tpch/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/travel_recommendations_realtime/', name='travel_recommendations_realtime/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/warmup/', name='warmup/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/weather/', name='weather/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/wiki/', name='wiki/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/wikipedia-datasets/', name='wikipedia-datasets/', size=0, modificationTime=1713121257454),
 FileInfo(path='dbfs:/databricks-datasets/wine-quality/', name='wine-quality/', size=0, modificationTime=1713121257455)]

In [0]:
dbutils.fs.ls("/databricks-datasets/adult")

[FileInfo(path='dbfs:/databricks-datasets/adult/README.md', name='README.md', size=2672, modificationTime=1455505834000),
 FileInfo(path='dbfs:/databricks-datasets/adult/adult.data', name='adult.data', size=3974305, modificationTime=1444261311000),
 FileInfo(path='dbfs:/databricks-datasets/adult/adult.test', name='adult.test', size=2003132, modificationTime=1455505834000)]

In [0]:
%fs

ls /databricks-datasets/adult/

path,name,size,modificationTime
dbfs:/databricks-datasets/adult/README.md,README.md,2672,1455505834000
dbfs:/databricks-datasets/adult/adult.data,adult.data,3974305,1444261311000
dbfs:/databricks-datasets/adult/adult.test,adult.test,2003132,1455505834000

In [0]:
adult_census_data = spark.read.csv("dbfs:/databricks-datasets/adult/adult.data", header=True)

type(adult_census_data)

pyspark.sql.dataframe.DataFrame

In [0]:
adult_census_rdd = adult_census_data.rdd

type(adult_census_rdd)

pyspark.rdd.RDD

In [0]:
adult_census_rdd.collect()

[Row(39='50',  State-gov=' Self-emp-not-inc',  77516=' 83311',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 13',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='38',  State-gov=' Private',  77516=' 215646',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Divorced',  Adm-clerical=' Handlers-cleaners',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='53',  State-gov=' Private',  77516=' 234721',  Bachelors=' 11th',  13=' 7',  Never-married=' Married-civ-spouse',  Adm-clerical=' Handlers-cleaners',  Not-in-family=' Husband',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='28',  State-gov=' Private',  77516=' 338409',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Wife',  White=' Black',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' Cuba',  <=50K=' <=50K'),
 Row(39='37',  State-gov=' Private',  77516=' 284582',  Bachelors=' Masters',  13=' 14',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Wife',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='49',  State-gov=' Private',  77516=' 160187',  Bachelors=' 9th',  13=' 5',  Never-married=' Married-spouse-absent',  Adm-clerical=' Other-service',  Not-in-family=' Not-in-family',  White=' Black',  Male=' Female',  2174=' 0',  0=' 0',  40=' 16',  United-States=' Jamaica',  <=50K=' <=50K'),
 Row(39='52',  State-gov=' Self-emp-not-inc',  77516=' 209642',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 45',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='31',  State-gov=' Private',  77516=' 45781',  Bachelors=' Masters',  13=' 14',  Never-married=' Never-married',  Adm-clerical=' Prof-specialty',  Not-in-family=' Not-in-family',  White=' White',  Male=' Female',  2174=' 14084',  0=' 0',  40=' 50',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='42',  State-gov=' Private',  77516=' 159449',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 5178',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='37',  State-gov=' Private',  77516=' 280464',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Husband',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 80',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='30',  State-gov=' State-gov',  77516=' 141297',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Husband',  White=' Asian-Pac-Islander',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' India',  <=50K=' >50K'),
 Row(39='23',  State-gov=' Private',  77516=' 122272',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Never-married',  Adm-clerical=' Adm-clerical',  Not-in-family=' Own-child',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 30',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='32',  State-gov=' Private',  77516=' 205019',  Bachelors=' Assoc-acdm',  13=' 12',  Never-married=' Never-married',  Adm-clerical=' Sales',  Not-in-family=' Not-in-family',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 50',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='40',  State-gov=' Private',  77516=' 121772',  Bachelors=' Assoc-voc',  13=' 11',  Never-married=' Married-civ-spouse',  Adm-clerical=' Craft-repair',  Not-in-family=' Husband',  White=' Asian-Pac-Islander',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' ?',  <=50K=' >50K'),
 Row(39='34',  State-gov=' Private',  77516=' 245487',  Bachelors=' 7th-8th',  13=' 4',  Never-married=' Married-civ-spouse',  Adm-clerical=' Transport-moving',  Not-in-family=' Husband',  White=' Amer-Indian-Eskimo',  Male=' Male',  2174=' 0',  0=' 0',  40=' 45',  United-States=' Mexico',  <=50K=' <=50K'),
 Row(39='25',  State-gov=' Self-emp-not-inc',  77516=' 176756',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Never-married',  Adm-clerical=' Farming-fishing',  Not-in-family=' Own-child',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 35',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='32',  State-gov=' Private',  77516=' 186824',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Never-married',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Unmarried',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='38',  State-gov=' Private',  77516=' 28887',  Bachelors=' 11th',  13=' 7',  Never-married=' Married-civ-spouse',  Adm-clerical=' Sales',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 50',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='43',  State-gov=' Self-emp-not-inc',  77516=' 292175',  Bachelors=' Masters',  13=' 14',  Never-married=' Divorced',  Adm-clerical=' Exec-managerial',  Not-in-family=' Unmarried',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 45',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='40',  State-gov=' Private',  77516=' 193524',  Bachelors=' Doctorate',  13=' 16',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 60',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='54',  State-gov=' Private',  77516=' 302146',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Separated',  Adm-clerical=' Other-service',  Not-in-family=' Unmarried',  White=' Black',  Male=' Female',  2174=' 0',  0=' 0',  40=' 20',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='35',  State-gov=' Federal-gov',  77516=' 76845',  Bachelors=' 9th',  13=' 5',  Never-married=' Married-civ-spouse',  Adm-clerical=' Farming-fishing',  Not-in-family=' Husband',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='43',  State-gov=' Private',  77516=' 117037',  Bachelors=' 11th',  13=' 7',  Never-married=' Married-civ-spouse',  Adm-clerical=' Transport-moving',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 2042',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='59',  State-gov=' Private',  77516=' 109015',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Divorced',  Adm-clerical=' Tech-support',  Not-in-family=' Unmarried',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='56',  State-gov=' Local-gov',  77516=' 216851',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Tech-support',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='19',  State-gov=' Private',  77516=' 168294',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Never-married',  Adm-clerical=' Craft-repair',  Not-in-family=' Own-child',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='54',  State-gov=' ?',  77516=' 180211',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' ?',  Not-in-family=' Husband',  White=' Asian-Pac-Islander',  Male=' Male',  2174=' 0',  0=' 0',  40=' 60',  United-States=' South',  <=50K=' >50K'),
 Row(39='39',  State-gov=' Private',  77516=' 367260',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Divorced',  Adm-clerical=' Exec-managerial',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 80',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='49',  State-gov=' Private',  77516=' 193366',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Craft-repair',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='23',  State-gov=' Local-gov',  77516=' 190709',  Bachelors=' Assoc-acdm',  13=' 12',  Never-married=' Never-married',  Adm-clerical=' Protective-serv',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 52',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='20',  State-gov=' Private',  77516=' 266015',  Bachelors=' Some-college',  13=' 10',  Never-married=' Never-married',  Adm-clerical=' Sales',  Not-in-family=' Own-child',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 44',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='45',  State-gov=' Private',  77516=' 386940',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Divorced',  Adm-clerical=' Exec-managerial',  Not-in-family=' Own-child',  White=' White',  Male=' Male',  2174=' 0',  0=' 1408',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='30',  State-gov=' Federal-gov',  77516=' 59951',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' Adm-clerical',  Not-in-family=' Own-child',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='22',  State-gov=' State-gov',  77516=' 311512',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' Other-service',  Not-in-family=' Husband',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 15',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='48',  State-gov=' Private',  77516=' 242406',  Bachelors=' 11th',  13=' 7',  Never-married=' Never-married',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Unmarried',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' Puerto-Rico',  <=50K=' <=50K'),
 Row(39='21',  State-gov=' Private',  77516=' 197200',  Bachelors=' Some-college',  13=' 10',  Never-married=' Never-married',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Own-child',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='19',  State-gov=' Private',  77516=' 544091',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-AF-spouse',  Adm-clerical=' Adm-clerical',  Not-in-family=' Wife',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 25',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='31',  State-gov=' Private',  77516=' 84154',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' Sales',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 38',  United-States=' ?',  <=50K=' >50K'),
 Row(39='48',  State-gov=' Self-emp-not-inc',  77516=' 265477',  Bachelors=' Assoc-acdm',  13=' 12',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='31',  State-gov=' Private',  77516=' 507875',  Bachelors=' 9th',  13=' 5',  Never-married=' Married-civ-spouse',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 43',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='53',  State-gov=' Self-emp-not-inc',  77516=' 88506',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='24',  State-gov=' Private',  77516=' 172987',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Tech-support',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 50',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='49',  State-gov=' Private',  77516=' 94638',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Separated',  Adm-clerical=' Adm-clerical',  Not-in-family=' Unmarried',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='25',  State-gov=' Private',  77516=' 289980',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Never-married',  Adm-clerical=' Handlers-cleaners',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 35',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='57',  State-gov=' Federal-gov',  77516=' 337895',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Husband',  White=' Black',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='53',  State-gov=' Private',  77516=' 144361',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 38',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='44',  State-gov=' Private',  77516=' 128354',  Bachelors=' Masters',  13=' 14',  Never-married=' Divorced',  Adm-clerical=' Exec-managerial',  Not-in-family=' Unmarried',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='41',  State-gov=' State-gov',  77516=' 101603',  Bachelors=' Assoc-voc',  13=' 11',  Never-married=' Married-civ-spouse',  Adm-clerical=' Craft-repair',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='29',  State-gov=' Private',  77516=' 271466',  Bachelors=' Assoc-voc',  13=' 11',  Never-married=' Never-married',  Adm-clerical=' Prof-specialty',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 43',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='25',  State-gov=' Private',  77516=' 32275',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Wife',  White=' Other',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='18',  State-gov=' Private',  77516=' 226956',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Never-married',  Adm-clerical=' Other-service',  Not-in-family=' Own-child',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 30',  United-States=' ?',  <=50K=' <=50K'),
 Row(39='47',  State-gov=' Private',  77516=' 51835',  Bachelors=' Prof-school',  13=' 15',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Wife',  White=' White',  Male=' Female',  2174=' 0',  0=' 1902',  40=' 60',  United-States=' Honduras',  <=50K=' >50K'),
 Row(39='50',  State-gov=' Federal-gov',  77516=' 251585',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Divorced',  Adm-clerical=' Exec-managerial',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 55',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='47',  State-gov=' Self-emp-inc',  77516=' 109832',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Divorced',  Adm-clerical=' Exec-managerial',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 60',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='43',  State-gov=' Private',  77516=' 237993',  Bachelors=' Some-college',  13=' 10',  Never-married=' Married-civ-spouse',  Adm-clerical=' Tech-support',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='46',  State-gov=' Private',  77516=' 216666',  Bachelors=' 5th-6th',  13=' 3',  Never-married=' Married-civ-spouse',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' Mexico',  <=50K=' <=50K'),
 Row(39='35',  State-gov=' Private',  77516=' 56352',  Bachelors=' Assoc-voc',  13=' 11',  Never-married=' Married-civ-spouse',  Adm-clerical=' Other-service',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' Puerto-Rico',  <=50K=' <=50K'),
 Row(39='41',  State-gov=' Private',  77516=' 147372',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Adm-clerical',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 48',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='30',  State-gov=' Private',  77516=' 188146',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Machine-op-inspct',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 5013',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='30',  State-gov=' Private',  77516=' 59496',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Sales',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 2407',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='32',  State-gov=' ?',  77516=' 293936',  Bachelors=' 7th-8th',  13=' 4',  Never-married=' Married-spouse-absent',  Adm-clerical=' ?',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' ?',  <=50K=' <=50K'),
 Row(39='48',  State-gov=' Private',  77516=' 149640',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Transport-moving',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='42',  State-gov=' Private',  77516=' 116632',  Bachelors=' Doctorate',  13=' 16',  Never-married=' Married-civ-spouse',  Adm-clerical=' Prof-specialty',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 45',  United-States=' United-States',  <=50K=' >50K'),
 Row(39='29',  State-gov=' Private',  77516=' 105598',  Bachelors=' Some-college',  13=' 10',  Never-married=' Divorced',  Adm-clerical=' Tech-support',  Not-in-family=' Not-in-family',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 58',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='36',  State-gov=' Private',  77516=' 155537',  Bachelors=' HS-grad',  13=' 9',  Never-married=' Married-civ-spouse',  Adm-clerical=' Craft-repair',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),
 Row(39='28',  State-gov=' Private',  77516=' 183175',  Bachelors=' Some-college',  13=' 10',  Never-married=' Divorced',  Adm-clerical=' Adm-clerical',  Not-in-family=' Not-in-family',  White=' White',  Male=' Female',  2174=' 0',  0=' 0',  40=' 40',  United-States=' United-States',  <=50K=' <=50K'),

In [0]:
adult_census_rdd.count()

32560

In [0]:
adult_census_rdd.first()

Row(39='50',  State-gov=' Self-emp-not-inc',  77516=' 83311',  Bachelors=' Bachelors',  13=' 13',  Never-married=' Married-civ-spouse',  Adm-clerical=' Exec-managerial',  Not-in-family=' Husband',  White=' White',  Male=' Male',  2174=' 0',  0=' 0',  40=' 13',  United-States=' United-States',  <=50K=' <=50K')

In [0]:
adult_census_rdd.map(lambda row: (row[1], row[3], row[5]))\
    .collect()

[(' Self-emp-not-inc', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' 11th', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' Private', ' 9th', ' Married-spouse-absent'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Masters', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' State-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Never-married'),
 (' Private', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' 7th-8th', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' 11th', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' Masters', ' Divorced'),
 (' Private', ' Doctorate', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Separated'),
 (' Federal-gov', ' 9th', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Local-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' ?', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Local-gov', ' Assoc-acdm', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Divorced'),
 (' Federal-gov', ' Some-college', ' Married-civ-spouse'),
 (' State-gov', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Married-AF-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' Assoc-acdm', ' Married-civ-spouse'),
 (' Private', ' 9th', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Separated'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Federal-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Masters', ' Divorced'),
 (' State-gov', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' Assoc-voc', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Prof-school', ' Married-civ-spouse'),
 (' Federal-gov', ' Bachelors', ' Divorced'),
 (' Self-emp-inc', ' HS-grad', ' Divorced'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' 5th-6th', ' Married-civ-spouse'),
 (' Private', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' ?', ' 7th-8th', ' Married-spouse-absent'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Doctorate', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-inc', ' Some-college', ' Married-civ-spouse'),
 (' ?', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Separated'),
 (' Self-emp-not-inc', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Married-civ-spouse'),
 (' ?', ' 10th', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Never-married'),
 (' Local-gov', ' 7th-8th', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Local-gov', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' Private', ' 9th', ' Never-married'),
 (' Federal-gov', ' Doctorate', ' Never-married'),
 (' Private', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Local-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Local-gov', ' Some-college', ' Never-married'),
 (' Self-emp-not-inc', ' Doctorate', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Assoc-acdm', ' Divorced'),
 (' Federal-gov', ' HS-grad', ' Never-married'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' Masters', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Self-emp-inc', ' HS-grad', ' Married-civ-spouse'),
 (' ?', ' 10th', ' Never-married'),
 (' Private', ' 11th', ' Never-married'),
 (' Local-gov', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' Prof-school', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' 9th', ' Married-civ-spouse'),
 (' Self-emp-inc', ' Some-college', ' Married-civ-spouse'),
 (' Local-gov', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' State-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Married-civ-spouse'),
 (' ?', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' Assoc-acdm', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Assoc-acdm', ' Divorced'),
 (' Federal-gov', ' Masters', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Self-emp-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Assoc-voc', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Widowed'),
 (' Private', ' 11th', ' Married-civ-spouse'),
 (' ?', ' Some-college', ' Divorced'),
 (' Local-gov', ' Some-college', ' Divorced'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' ?', ' HS-grad', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Self-emp-not-inc', ' Some-college', ' Separated'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' Bachelors', ' Separated'),
 (' ?', ' 1st-4th', ' Divorced'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Self-emp-inc', ' Masters', ' Divorced'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Self-emp-not-inc', ' Masters', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Federal-gov', ' Assoc-acdm', ' Never-married'),
 (' State-gov', ' Masters', ' Widowed'),
 (' Private', ' 11th', ' Never-married'),
 (' Local-gov', ' Assoc-voc', ' Widowed'),
 (' Private', ' HS-grad', ' Never-married'),
 (' State-gov', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' State-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-spouse-absent'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Local-gov', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' 7th-8th', ' Married-civ-spouse'),
 (' Federal-gov', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' Bachelors', ' Divorced'),
 (' ?', ' Bachelors', ' Divorced'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' State-gov', ' Doctorate', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Local-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Federal-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' 5th-6th', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Federal-gov', ' Masters', ' Never-married'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Never-married'),
 (' Private', ' Masters', ' Never-married'),
 (' ?', ' HS-grad', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Local-gov', ' Some-college', ' Never-married'),
 (' State-gov', ' HS-grad', ' Divorced'),
 (' Private', ' 11th', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Self-emp-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Never-married'),
 (' Local-gov', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-inc', ' 7th-8th', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Divorced'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' 10th', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' ?', ' 1st-4th', ' Divorced'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Local-gov', ' Preschool', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' ?', ' 10th', ' Divorced'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Assoc-voc', ' Widowed'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' 11th', ' Separated'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' Prof-school', ' Never-married'),
 (' State-gov', ' HS-grad', ' Married-civ-spouse'),
 (' State-gov', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Local-gov', ' Masters', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' State-gov', ' Assoc-acdm', ' Married-civ-spouse'),
 (' ?', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Prof-school', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Local-gov', ' 10th', ' Widowed'),
 (' Local-gov', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Separated'),
 (' Private', ' Assoc-voc', ' Widowed'),
 (' Private', ' 7th-8th', ' Divorced'),
 (' Private', ' Bachelors', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Married-civ-spouse'),
 (' Self-emp-inc', ' Some-college', ' Married-civ-spouse'),
 (' ?', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' 9th', ' Never-married'),
 (' Self-emp-not-inc', ' Masters', ' Married-civ-spouse'),
 (' Local-gov', ' Masters', ' Never-married'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Local-gov', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Assoc-acdm', ' Divorced'),
 (' Private', ' Bachelors', ' Divorced'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Federal-gov', ' Masters', ' Married-civ-spouse'),
 (' Private', ' Prof-school', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' 7th-8th', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Local-gov', ' Bachelors', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-inc', ' Bachelors', ' Divorced'),
 (' ?', ' Masters', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' Assoc-acdm', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Never-married'),
 (' Private', ' Assoc-acdm', ' Married-civ-spouse'),
 (' Self-emp-inc', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' ?', ' Some-college', ' Never-married'),
 (' Self-emp-not-inc', ' Bachelors', ' Divorced'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Self-emp-not-inc', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' 5th-6th', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Widowed'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' 11th', ' Never-married'),
 (' Self-emp-not-inc', ' Masters', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' ?', ' Assoc-voc', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' Assoc-voc', ' Never-married'),
 (' Local-gov', ' 10th', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' 5th-6th', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Masters', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Assoc-acdm', ' Never-married'),
 (' Private', ' Assoc-voc', ' Married-civ-spouse'),
 (' State-gov', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' State-gov', ' Some-college', ' Never-married'),
 (' Self-emp-not-inc', ' Bachelors', ' Never-married'),
 (' ?', ' 11th', ' Married-civ-spouse'),
 (' ?', ' Assoc-voc', ' Divorced'),
 (' Private', ' Assoc-acdm', ' Married-spouse-absent'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Local-gov', ' 11th', ' Married-civ-spouse'),
 (' ?', ' Bachelors', ' Married-civ-spouse'),
 (' Federal-gov', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' 11th', ' Widowed'),
 (' Private', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' 9th', ' Married-civ-spouse'),
 (' Private', ' 10th', ' Married-civ-spouse'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Divorced'),
 (' Private', ' HS-grad', ' Married-spouse-absent'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Assoc-acdm', ' Never-married'),
 (' Private', ' Bachelors', ' Divorced'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Federal-gov', ' Some-college', ' Never-married'),
 (' Private', ' 11th', ' Never-married'),
 (' State-gov', ' Assoc-voc', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Local-gov', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Self-emp-not-inc', ' Masters', ' Divorced'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Divorced'),
 (' Private', ' 5th-6th', ' Divorced'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' Local-gov', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Separated'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Private', ' Bachelors', ' Never-married'),
 (' Self-emp-not-inc', ' Assoc-acdm', ' Separated'),
 (' State-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Never-married'),
 (' Private', ' Some-college', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Divorced'),
 (' ?', ' HS-grad', ' Never-married'),
 (' Private', ' Bachelors', ' Married-civ-spouse'),
 (' Self-emp-inc', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Some-college', ' Never-married'),
 (' Private', ' Some-college', ' Never-married'),
 (' State-gov', ' Bachelors', ' Married-civ-spouse'),
 (' Private', ' Assoc-voc', ' Divorced'),
 (' Private', ' 7th-8th', ' Married-civ-spouse'),
 (' Private', ' Masters', ' Married-civ-spouse'),
 (' Private', ' HS-grad', ' Married-civ-spouse'),
 (' Self-emp-not-inc', ' HS-grad', ' Married-civ-spouse'),
 (' ?', ' Some-college', ' Married-civ-spouse'),

In [0]:
dbutils.fs.ls("databricks-datasets/bikeSharing/data-001")

[FileInfo(path='dbfs:/databricks-datasets/bikeSharing/data-001/day.csv', name='day.csv', size=57569, modificationTime=1455505837000),
 FileInfo(path='dbfs:/databricks-datasets/bikeSharing/data-001/hour.csv', name='hour.csv', size=1156736, modificationTime=1455505837000)]

In [0]:
bike_sharing_data = spark.read.format('csv')\
    .option("inferSchema", "True")\
    .option("header", "True")\
    .option("sep", ",")\
    .load("/databricks-datasets/bikeSharing/data-001/day.csv")

In [0]:
bike_sharing_data.show()

+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
|instant|    dteday|season| yr|mnth|holiday|weekday|workingday|weathersit|    temp|   atemp|     hum|windspeed|casual|registered| cnt|
+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
|      1|2011-01-01|     1|  0|   1|      0|      6|         0|         2|0.344167|0.363625|0.805833| 0.160446|   331|       654| 985|
|      2|2011-01-02|     1|  0|   1|      0|      0|         0|         2|0.363478|0.353739|0.696087| 0.248539|   131|       670| 801|
|      3|2011-01-03|     1|  0|   1|      0|      1|         1|         1|0.196364|0.189405|0.437273| 0.248309|   120|      1229|1349|
|      4|2011-01-04|     1|  0|   1|      0|      2|         1|         1|     0.2|0.212122|0.590435| 0.160296|   108|      1454|1562|
|      5|2011-01-05|     1|  0|   1|      0|      3|         1|         1|0.226957| 0.22927|0.436957|   0.1869|    82|      1518|1600|
|      6|2011-01-06|     1|  0|   1|      0|      4|         1|         1|0.204348|0.233209|0.518261|0.0895652|    88|      1518|1606|
|      7|2011-01-07|     1|  0|   1|      0|      5|         1|         2|0.196522|0.208839|0.498696| 0.168726|   148|      1362|1510|
|      8|2011-01-08|     1|  0|   1|      0|      6|         0|         2|   0.165|0.162254|0.535833| 0.266804|    68|       891| 959|
|      9|2011-01-09|     1|  0|   1|      0|      0|         0|         1|0.138333|0.116175|0.434167|  0.36195|    54|       768| 822|
|     10|2011-01-10|     1|  0|   1|      0|      1|         1|         1|0.150833|0.150888|0.482917| 0.223267|    41|      1280|1321|
|     11|2011-01-11|     1|  0|   1|      0|      2|         1|         2|0.169091|0.191464|0.686364| 0.122132|    43|      1220|1263|
|     12|2011-01-12|     1|  0|   1|      0|      3|         1|         1|0.172727|0.160473|0.599545| 0.304627|    25|      1137|1162|
|     13|2011-01-13|     1|  0|   1|      0|      4|         1|         1|   0.165|0.150883|0.470417|    0.301|    38|      1368|1406|
|     14|2011-01-14|     1|  0|   1|      0|      5|         1|         1| 0.16087|0.188413|0.537826| 0.126548|    54|      1367|1421|
|     15|2011-01-15|     1|  0|   1|      0|      6|         0|         2|0.233333|0.248112| 0.49875| 0.157963|   222|      1026|1248|
|     16|2011-01-16|     1|  0|   1|      0|      0|         0|         1|0.231667|0.234217| 0.48375| 0.188433|   251|       953|1204|
|     17|2011-01-17|     1|  0|   1|      1|      1|         0|         2|0.175833|0.176771|  0.5375| 0.194017|   117|       883|1000|
|     18|2011-01-18|     1|  0|   1|      0|      2|         1|         2|0.216667|0.232333|0.861667| 0.146775|     9|       674| 683|
|     19|2011-01-19|     1|  0|   1|      0|      3|         1|         2|0.292174|0.298422|0.741739| 0.208317|    78|      1572|1650|
|     20|2011-01-20|     1|  0|   1|      0|      4|         1|         2|0.261667| 0.25505|0.538333| 0.195904|    83|      1844|1927|
+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
only showing top 20 rows

In [0]:
bike_sharing_data.show(3)

+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
|instant|    dteday|season| yr|mnth|holiday|weekday|workingday|weathersit|    temp|   atemp|     hum|windspeed|casual|registered| cnt|
+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
|      1|2011-01-01|     1|  0|   1|      0|      6|         0|         2|0.344167|0.363625|0.805833| 0.160446|   331|       654| 985|
|      2|2011-01-02|     1|  0|   1|      0|      0|         0|         2|0.363478|0.353739|0.696087| 0.248539|   131|       670| 801|
|      3|2011-01-03|     1|  0|   1|      0|      1|         1|         1|0.196364|0.189405|0.437273| 0.248309|   120|      1229|1349|
+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
only showing top 3 rows

In [0]:
bike_sharing_data_selected = bike_sharing_data.select('season', 'holiday', 'cnt')

In [0]:
bike_sharing_data_selected.show(3)

+------+-------+----+
|season|holiday| cnt|
+------+-------+----+
|     1|      0| 985|
|     1|      0| 801|
|     1|      0|1349|
+------+-------+----+
only showing top 3 rows

In [0]:
bike_sharing_data.filter(bike_sharing_data['cnt'] > 1000).show(3)

+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
|instant|    dteday|season| yr|mnth|holiday|weekday|workingday|weathersit|    temp|   atemp|     hum|windspeed|casual|registered| cnt|
+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
|      3|2011-01-03|     1|  0|   1|      0|      1|         1|         1|0.196364|0.189405|0.437273| 0.248309|   120|      1229|1349|
|      4|2011-01-04|     1|  0|   1|      0|      2|         1|         1|     0.2|0.212122|0.590435| 0.160296|   108|      1454|1562|
|      5|2011-01-05|     1|  0|   1|      0|      3|         1|         1|0.226957| 0.22927|0.436957|   0.1869|    82|      1518|1600|
+-------+----------+------+---+----+-------+-------+----------+----------+--------+--------+--------+---------+------+----------+----+
only showing top 3 rows

In [0]:
# Transformation is when assigning a value to a variable which based on RDD it will create a copy of the original file where the original file #is imutable but the copy of the file is mutable.

# Action on the other hand is when we execute an operation on the record and it will take few time to execute the command

# Note: The above data are built in dataset

# Data in right menue help us to add data to the database
# Dataset can be add but should be enable first [Setting -> Admin Console -> Workspace Setting -> DBFS File Browser: (set to enable)]
    # Note: Referesh page to take effect

# Data if you now check data menue you will see two tab now 'Database Tables' and 'DBFS'

# To upload dataset in databricks within Notebook click [ file -> upload; upload dataset; copy the path from opened window

# Download dataset from www.kaggle.com

In [0]:
bike_sharing_data.select('season', 'holiday', 'cnt')\
    .limit(3)\
    .show()

+------+-------+----+
|season|holiday| cnt|
+------+-------+----+
|     1|      0| 985|
|     1|      0| 801|
|     1|      0|1349|
+------+-------+----+

In [0]:
bike_sharing_data.filter(bike_sharing_data['season'].isNull())\
    .show()

+-------+------+------+---+----+-------+-------+----------+----------+----+-----+---+---------+------+----------+---+
|instant|dteday|season| yr|mnth|holiday|weekday|workingday|weathersit|temp|atemp|hum|windspeed|casual|registered|cnt|
+-------+------+------+---+----+-------+-------+----------+----------+----+-----+---+---------+------+----------+---+
+-------+------+------+---+----+-------+-------+----------+----------+----+-----+---+---------+------+----------+---+

In [0]:
bike_sharing_data = bike_sharing_data.dropna()

bike_sharing_data.count()

731

In [0]:
bike_sharing_data_copy = bike_sharing_data

bike_sharing_data_copy.select('season', 'holiday', 'cnt')\
    .withColumnRenamed('season', 'season_ahmad')\
    .withColumnRenamed('holiday', 'holiday_ahmad')\
    .show(3)

+------------+-------------+----+
|season_ahmad|holiday_ahmad| cnt|
+------------+-------------+----+
|           1|            0| 985|
|           1|            0| 801|
|           1|            0|1349|
+------------+-------------+----+
only showing top 3 rows

In [0]:
bike_sharing_data_copy.select('season', 'holiday', 'cnt')\
    .withColumn("season_copy", bike_sharing_data_copy['season'])\
    .show(3)

+------+-------+----+-----------+
|season|holiday| cnt|season_copy|
+------+-------+----+-----------+
|     1|      0| 985|          1|
|     1|      0| 801|          1|
|     1|      0|1349|          1|
+------+-------+----+-----------+
only showing top 3 rows

In [0]:
bike_sharing_data_copy.select('season', 'holiday', 'cnt')\
    .orderBy(bike_sharing_data_copy['cnt'].asc())\
    .show(3)

+------+-------+---+
|season|holiday|cnt|
+------+-------+---+
|     4|      0| 22|
|     1|      0|431|
|     1|      0|441|
+------+-------+---+
only showing top 3 rows

In [0]:
bike_sharing_data_copy.groupBy('cnt').count().show(5)

+----+-----+
| cnt|count|
+----+-----+
|2659|    1|
| 623|    1|
|2999|    1|
|1650|    1|
|5345|    1|
+----+-----+
only showing top 5 rows

In [0]:
bike_sharing_data_copy.groupBy('cnt').agg({'season': 'sum'}).show(5)

+----+-----------+
| cnt|sum(season)|
+----+-----------+
|2659|          4|
| 623|          1|
|2999|          1|
|1650|          1|
|5345|          3|
+----+-----------+
only showing top 5 rows

In [0]:
bike_sharing_data_copy.groupBy('cnt').count().write.csv('dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv')

In [0]:
print(dbutils.fs.ls('dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv'))

[FileInfo(path='dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/_SUCCESS', name='_SUCCESS', size=0, modificationTime=1713125998000), FileInfo(path='dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/_committed_5927010642527955146', name='_committed_5927010642527955146', size=112, modificationTime=1713125998000), FileInfo(path='dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/_started_5927010642527955146', name='_started_5927010642527955146', size=0, modificationTime=1713125998000), FileInfo(path='dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/part-00000-tid-5927010642527955146-ba7ea0b3-a3ca-4545-8b24-41eb5911c178-32-1-c000.csv', name='part-00000-tid-5927010642527955146-ba7ea0b3-a3ca-4545-8b24-41eb5911c178-32-1-c000.csv', size=4853, modificationTime=1713125998000)]

In [0]:
print(dbutils.fs.ls('dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/_started_5927010642527955146'))

[FileInfo(path='dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/_started_5927010642527955146', name='_started_5927010642527955146', size=0, modificationTime=1713125998000)]

In [0]:
print(dbutils.fs.head('dbfs:/FileStore/shared_uploads/ahmad/ahmad_test.csv/part-00000-tid-5927010642527955146-ba7ea0b3-a3ca-4545-8b24-41eb5911c178-32-1-c000.csv'))

2659,1
623,1
2999,1
1650,1
5345,1
5117,1
3761,1
6825,1
4186,1
6598,1
6597,1
1977,2
4294,1
5217,1
3425,1
5740,1
7333,1
2914,1
2802,1
5847,2
6864,1
7109,1
4097,1
7736,1
1787,1
1005,1
3577,1
4725,1
4401,2
4182,1
4713,1
5298,1
7132,1
5375,1
683,1
2739,1
2294,1
4773,1
7865,1
7359,1
7499,1
6639,1
4917,1
4153,1
5918,1
4169,1
6460,1
5585,1
6664,1
4326,1
2209,1
5936,1
7460,1
1510,1
5119,2
4826,1
3485,1
6855,1
8395,1
8090,1
5895,1
1708,1
3403,1
3624,1
4758,2
3811,1
5875,1
1927,1
3387,1
4866,1
5823,1
2134,1
3744,1
3669,1
2169,1
3922,1
7290,1
4036,1
3727,1
5892,1
7424,1
2496,1
3456,1
6904,1
2236,1
5087,1
3228,1
7055,1
5062,1
6572,1
7504,1
6852,1
4669,1
4363,1
822,1
3239,1
2227,1
3071,1
6606,1
4120,1
5905,1
7446,1
7216,1
1550,1
4788,1
5302,1
6273,1
6891,1
22,1
1796,1
4521,1
7058,1
4727,1
5633,1
5099,1
7580,1
4040,1
5786,1
5084,1
5102,1
4459,2
5478,1
1944,1
2192,1
4507,1
2056,1
6536,2
6917,1
4844,1
3940,1
7347,1
7691,1
7001,1
3095,1
4451,1
3956,1
6778,1
5315,1
4656,1
7335,1
7570,1
5047,1
5499,1
6234,1
5611,1
4338,1
6230,1
7720,1
2475,1
1812,1
1683,1
4475,1
3570,1
6457,1
5336,1
5204,1
4569,1
6227,1
6786,1
5255,1
2633,1
7261,1
7733,1
4304,1
3272,1
2471,1
2455,1
4151,1
7286,1
5992,1
3786,1
2210,1
8009,1
7572,1
4966,1
4570,1
5382,1
4220,1
6359,1
4672,1
1834,1
1749,1
3659,1
6053,1
7436,1
3115,1
7852,1
4094,1
1349,1
5538,1
4905,1
5445,1
2729,1
1461,1
2808,1
4991,1
4258,1
4352,1
6824,2
5424,1
431,1
1538,1
4639,1
1301,1
4118,1
3709,1
6691,1
6734,1
6779,1
920,1
3613,1
6978,1
7006,1
3649,1
2177,1
1917,1
5225,1
2485,1
6370,1
1605,1
6043,2
4839,1
4765,1
1951,1
7112,1
1167,1
3663,1
6436,1
5010,1
3894,1
1360,1
3249,1
2368,1
1341,1
959,1
2252,1
4660,1
6879,1
3750,1
4608,1
4390,1
754,1
5463,1
1807,1
4381,1
6304,1
4322,1
6299,1
3243,1
4318,1
2895,1
2743,1
6660,1
5713,1
1321,1
1530,1
4191,1
3574,1
5728,1
7870,1
3285,1
1529,1
5572,1
4460,1
4629,1
4308,1
3333,1
5743,1
5870,1
7148,1
6140,1
3310,1
6772,1
7765,1
7693,1
4195,2
7641,1
1263,1
4073,2
4595,1
3907,1
2732,1
5495,1
1635,1
4864,1
4648,1
6770,1
2703,1
3717,1
7393,1
5146,1
1913,1
3784,2
4694,1
5409,2
3163,1
7538,1
4717,1
7907,1
6392,1
1248,1
3805,1
5191,2
3068,2
5180,1
6203,1
7509,1
1406,1
3141,1
5342,1
4576,1
4511,1
5423,1
4127,1
4940,1
4023,1
7264,1
1600,1
3620,1
1969,1
5515,1
3392,1
7429,1
7363,1
7328,1
1865,1
3958,1
3606,1
6784,1
5532,1
1589,1
1815,1
7494,1
7767,1
7444,1
1536,1
4274,2
5130,1
3740,1
2298,1
4075,1
2947,1
7665,1
5558,1
6235,1
4840,1
7605,1
3129,1
6591,2
5531,1
986,1
4068,1
3422,1
3423,1
6031,1
441,1
1096,2
5923,1
4916,1
6207,1
6685,1
2402,1
4881,1
7030,1
5319,1
2046,1
4333,1
4592,1
5511,1
3926,1
3830,1
2424,2
4066,1
6966,1
3959,1
1996,1
7804,1
981,1
1685,2
4105,1
2933,1
3292,1
4334,1
6857,1
7713,1
2034,1
2935,1
2832,1
1795,1
2918,1
4109,1
6421,1
1000,1
3389,1
8173,1
627,1
6312,1
7105,1
7461,1
2277,1
4058,1
4010,1
4150,1
1495,1
3777,1
6093,1
4359,1
3117,1
2429,1
3331,1
4154,1
5976,1
4539,1
5668,1
5501,1
3944,1
4780,1
7836,1
2077,2
1872,1
4760,1
4035,1
3867,1
6211,1
4086,1
1317,1
6624,1
7639,1
7442,1
7350,1
5035,1
1746,1
4433,1
4123,1
4968,1
5362,1
3840,1
1607,1
1985,1
5058,1
5260,2
6869,1
4845,1
4661,1
3598,1
7375,1
3126,1
4714,1
4687,1
8120,1
1098,1
3855,1
5008,1
5305,1
2395,1
3644,1
2431,1
3429,1
3982,1
6861,1
3190,1
5557,1
4456,1
4579,1
4763,1
4586,1
2311,1
7534,2
6034,1
5138,1
4630,1
4803,1
4790,1
3351,2
5020,1
4270,1
6565,1
6241,1
2114,1
1421,1
1543,1
3510,1
5323,1
795,1
3974,2
4862,1
5267,1
1501,1
4891,1
2689,1
7338,1
7013,1
5629,1
4400,1
3267,1
3204,1
4332,1
4590,1
4067,1
5259,1
4708,1
2133,1
4187,1
6290,1
5312,2
4563,1
4098,2
3322,1
4792,1
3872,1
6398,1
2843,1
4972,1
8555,1
5686,1
1450,1
6569,1
5810,1
4342,1
3820,1
7175,1
2744,1
4553,1
3767,1
6969,1
1562,1
1712,1
2132,1
4649,2
3641,1
2927,1
4835,1
5202,2
1115,1
4205,1
7525,1
7282,1
1027,1
8227,1
4339,1
1471,1
5046,1
2594,1
2432,1
5464,1
801,1
4189,1
3915,1
6296,1
4458,1
2710,1
3614,1
2660,1
3487,1
4990,1
7702,1
1623,1
1446,1
4492,1
2765,1
7697,1
1842,1
7273,1
1162,2
4548,1
4634,1
5687,1
5729,1
3544,1
4785,1
6041,1
7421,1
7403,1
5698,2
4362,1
5805,1
4541,1
3747,1
4378,1
6073,1
2121,1
4486,1
4266,1
1472,1
3873,1
2028,1
3409,1
4575,1
4375,1
5026,1
6830,1
7591,1
1693,1
7458,1
3623,1
3785,1
6192,1
8156,1
2416,1
8714,1
1606,1
4302,1
7582,1
5986,1
5634,1
506,1
2493,1
4509,1
6889,1
2162,1
4906,1
1817,1
6196,1
6883,2
4833,1
4665,1
2302,1
2115,1
5115,2
6530,1
4046,1
4679,1
7965,1
6269,1
4128,1
3348,1
1011,1
4911,1
3520,1
2792,1
5459,1
7415,1
985,1
3005,1
3372,1
4978,1
2566,1
3214,2
4996,1
5041,1
4748,1
7410,1
605,1
6169,1
1851,1
3194,1
7592,1
8167,1
1526,1
4677,1
2423,1
6871,1
5170,1
1891,1
7498,1
4744,1
2913,1
8362,1
6233,1
8294,1
4602,1
705,1
7384,1
1013,1
6133,1
5169,1
6998,1
2425,2
4795,1
3831,1
6118,1
4549,1
1204,1
4985,1
5582,1
1416,1
3368,1
6544,1
2417,1
4367,1
5566,1
5107,1
7129,1
1107,1
3542,1
7040,1
3846,1
4484,1
3053,1
3523,1
2376,1
3376,1
6153,1
7466,1
3910,1
4585,1

In [0]:
# For the above command we need to find the Data tab and go inside DBFS and navigate to file and copy the resources name.

# Create New Table -> upload new file

In [0]:
online_foods = spark.sql('select * from default.onlinefoods')

In [0]:
display(online_foods)

Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback
20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive
24,Female,Single,Student,Below Rs.10000,Graduate,3,12.977,77.5773,560009,Yes,Positive
22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative
22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive
22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.985,77.5533,560010,Yes,Positive
27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive
22,Male,Single,Student,No Income,Graduate,3,12.977,77.5773,560009,Yes,Positive
24,Female,Single,Student,No Income,Post Graduate,3,12.9828,77.6131,560042,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive
22,Female,Single,Student,No Income,Post Graduate,5,12.985,77.5533,560010,Yes,Positive
23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.977,77.5773,560009,Yes,Negative
23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive
21,Male,Single,Student,No Income,Graduate,4,12.977,77.5773,560009,Yes,Positive
23,Female,Single,Self Employeed,10001 to 25000,Post Graduate,5,12.9438,77.5738,560004,Yes,Positive
24,Female,Single,Student,No Income,Post Graduate,6,12.8893,77.6399,560068,Yes,Positive
28,Female,Single,Employee,25001 to 50000,Post Graduate,2,12.9783,77.6408,560038,Yes,Positive
23,Female,Single,Student,No Income,Graduate,3,12.982,77.6256,560008,Yes,Negative
25,Male,Single,Student,No Income,Graduate,4,12.8988,77.5764,560078,Yes,Negative
21,Female,Single,Student,Below Rs.10000,Post Graduate,1,12.9783,77.6408,560038,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,4,13.0298,77.6047,560032,Yes,Positive
22,Female,Single,Student,No Income,Graduate,4,12.9983,77.6409,560033,Yes,Positive
23,Male,Single,Student,No Income,Graduate,4,12.9925,77.5633,560021,Yes,Positive
21,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9306,77.5434,560085,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,3,12.982,77.6256,560008,Yes,Positive
22,Female,Single,Student,No Income,Post Graduate,5,12.9353,77.5585,560050,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,3,12.9155,77.5135,560098,Yes,Positive
23,Female,Single,Employee,10001 to 25000,Graduate,3,12.9854,77.7081,560048,Yes,Positive
22,Male,Single,Student,Below Rs.10000,Post Graduate,4,13.0019,77.5713,560003,Yes,Positive
22,Female,Single,Employee,10001 to 25000,Graduate,5,12.9698,77.75,560066,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,4,12.9783,77.6408,560038,Yes,Positive
25,Male,Married,Employee,More than 50000,Ph.D,4,12.9261,77.6221,560034,Yes,Positive
22,Female,Single,Student,10001 to 25000,Post Graduate,5,12.985,77.5533,560010,Yes,Positive
22,Female,Single,Student,No Income,Post Graduate,2,12.9119,77.6446,560102,Yes,Positive
25,Male,Single,Student,10001 to 25000,Post Graduate,3,12.9306,77.5434,560085,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,5,12.977,77.5773,560009,No,Positive
32,Female,Prefer not to say,House wife,No Income,Graduate,5,12.982,77.6256,560008,Yes,Negative
23,Female,Single,Student,No Income,Post Graduate,3,12.9438,77.5738,560004,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,12.8988,77.5764,560078,Yes,Positive
30,Male,Married,Self Employeed,More than 50000,Uneducated,4,12.9662,77.6068,560025,Yes,Negative
23,Male,Single,Student,No Income,Graduate,3,12.9565,77.5484,560026,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,4,12.9925,77.5633,560021,Yes,Positive
22,Female,Single,Student,No Income,Post Graduate,5,12.985,77.5533,560010,Yes,Positive
22,Male,Single,Student,No Income,Graduate,5,12.985,77.5533,560010,Yes,Positive
27,Female,Married,Self Employeed,10001 to 25000,Post Graduate,2,12.9261,77.6221,560034,Yes,Positive
24,Female,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,2,12.977,77.5773,560009,Yes,Positive
23,Female,Single,Student,No Income,Graduate,3,12.982,77.6256,560008,Yes,Negative
22,Female,Single,Student,10001 to 25000,Post Graduate,5,12.985,77.5533,560010,Yes,Positive
23,Female,Single,Student,No Income,Graduate,5,13.0206,77.6479,560043,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,2,12.977,77.5773,560009,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,2,12.9635,77.5821,560002,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,3,12.9306,77.5434,560085,Yes,Positive
28,Female,Married,Student,No Income,Graduate,2,13.0067,77.545,560086,Yes,Positive
22,Female,Single,Student,No Income,Post Graduate,1,12.8845,77.6036,560076,Yes,Positive
24,Female,Single,Student,No Income,Graduate,3,12.977,77.5773,560009,Yes,Positive
31,Male,Married,Employee,More than 50000,Ph.D,5,12.9119,77.6446,560102,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,4,13.0067,77.545,560086,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,3,12.8845,77.6036,560076,Yes,Positive
23,Male,Single,Student,25001 to 50000,Post Graduate,1,13.0158,77.539,560096,Yes,Positive
23,Male,Single,Student,No Income,Graduate,4,12.9343,77.6044,560029,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,2,13.0019,77.5713,560003,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,6,13.0012,77.5995,560046,Yes,Positive
24,Male,Single,Employee,10001 to 25000,Graduate,4,12.9442,77.6076,560030,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,13.0487,77.5923,560024,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,13.0487,77.5923,560024,Yes,Positive
24,Female,Married,Employee,More than 50000,Ph.D,4,12.9438,77.5738,560004,Yes,Positive
22,Male,Single,Student,No Income,Graduate,4,12.9889,77.5741,560020,Yes,Positive
24,Female,Single,Student,10001 to 25000,Post Graduate,3,12.9335,77.5691,560028,No,Positive
25,Female,Single,Student,No Income,Post Graduate,3,12.9766,77.5993,560001,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,2,12.8845,77.6036,560076,Yes,Positive
26,Male,Single,Student,No Income,Post Graduate,4,13.0019,77.5713,560003,Yes,Positive
24,Female,Single,Student,25001 to 50000,Post Graduate,3,13.102,77.5864,560064,Yes,Positive
26,Male,Single,Student,No Income,Post Graduate,4,12.9048,77.6821,560036,Yes,Positive
21,Male,Single,Student,No Income,Graduate,4,12.977,77.5773,560009,Yes,Positive
22,Female,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,5,12.9337,77.59,560011,Yes,Positive
24,Male,Single,Student,10001 to 25000,Post Graduate,4,12.9037,77.5376,560061,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,3,12.9343,77.6044,560029,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,3,12.9438,77.5738,560004,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
24,Female,Single,Student,No Income,Post Graduate,4,12.9783,77.6408,560038,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,5,12.9337,77.59,560011,Yes,Positive
25,Male,Single,Student,No Income,Graduate,1,12.977,77.5773,560009,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,5,12.977,77.5773,560009,No,Positive
28,Male,Married,Self Employeed,10001 to 25000,Graduate,2,13.0289,77.54,560022,No,Negative
27,Female,Prefer not to say,Employee,25001 to 50000,Post Graduate,5,13.0289,77.54,560022,No,Positive
26,Male,Single,Self Employeed,10001 to 25000,Ph.D,1,12.9698,77.75,560066,No,Positive
22,Male,Single,Student,No Income,Post Graduate,2,12.977,77.5773,560009,Yes,Positive
24,Female,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,1,12.9561,77.5921,560027,Yes,Positive
25,Male,Single,Student,No Income,Graduate,1,12.977,77.5773,560009,Yes,Positive
23,Female,Single,Student,No Income,Graduate,5,13.0206,77.6479,560043,Yes,Positive
23,Female,Single,Student,No Income,Graduate,5,13.0206,77.6479,560043,Yes,Positive
26,Male,Married,Employee,25001 to 50000,Graduate,5,12.9579,77.6309,560007,No,Positive
32,Female,Married,House wife,No Income,Uneducated,3,13.014,77.5658,560012,No,Positive
24,Female,Single,Student,10001 to 25000,Post Graduate,3,12.9335,77.5691,560028,No,Positive
23,Male,Single,Student,No Income,Post Graduate,2,12.9442,77.6076,560030,Yes,Positive
22,Female,Single,Employee,10001 to 25000,Graduate,3,12.9698,77.75,560066,Yes,Positive
24,Female,Single,Student,No Income,Ph.D,3,12.9438,77.5738,560004,Yes,Positive
26,Male,Single,Employee,25001 to 50000,Graduate,2,12.9261,77.6221,560034,Yes,Negative
28,Male,Married,Employee,More than 50000,Graduate,3,12.9698,77.75,560066,No,Positive
26,Male,Single,Employee,More than 50000,Post Graduate,2,12.9698,77.75,560066,No,Positive
25,Male,Single,Student,No Income,Post Graduate,1,12.9343,77.6044,560029,Yes,Positive
25,Male,Single,Employee,Below Rs.10000,Graduate,2,12.9698,77.75,560066,No,Positive
18,Male,Single,Student,No Income,Graduate,5,12.9635,77.5821,560002,Yes,Positive
21,Male,Single,Student,No Income,Post Graduate,4,12.977,77.5773,560009,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,1,12.9343,77.6044,560029,Yes,Positive
25,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9925,77.5633,560021,Yes,Positive
23,Female,Single,Student,No Income,Graduate,5,13.0206,77.6479,560043,Yes,Positive
23,Male,Single,Employee,10001 to 25000,Post Graduate,2,12.985,77.5533,560010,Yes,Positive
25,Female,Married,Employee,25001 to 50000,Graduate,4,12.9551,77.6593,560017,No,Negative
31,Female,Married,House wife,No Income,School,5,13.0289,77.54,560022,Yes,Positive
24,Male,Prefer not to say,Self Employeed,More than 50000,Ph.D,2,13.0138,77.5877,560006,No,Positive
32,Female,Married,Employee,25001 to 50000,Graduate,5,12.9261,77.6221,560034,Yes,Positive
25,Male,Single,Employee,25001 to 50000,Graduate,3,12.9766,77.5993,560001,Yes,Positive
27,Female,Married,Self Employeed,More than 50000,Graduate,5,12.9766,77.5993,560001,No,Positive
26,Male,Single,Self Employeed,25001 to 50000,Graduate,3,12.9766,77.5993,560001,Yes,Positive
26,Female,Single,Self Employeed,25001 to 50000,Post Graduate,3,12.9635,77.5821,560002,Yes,Positive
32,Male,Married,Employee,More than 50000,Ph.D,5,12.9635,77.5821,560002,Yes,Negative
24,Male,Married,Self Employeed,More than 50000,Ph.D,6,12.9635,77.5821,560002,No,Negative
27,Female,Married,Self Employeed,25001 to 50000,Graduate,3,12.9635,77.5821,560002,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
25,Male,Single,Student,No Income,Post Graduate,4,12.977,77.5773,560009,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,13.0487,77.5923,560024,Yes,Positive
28,Male,Married,Employee,More than 50000,Post Graduate,3,13.0019,77.5713,560003,Yes,Positive
32,Female,Married,Employee,More than 50000,Graduate,1,13.0019,77.5713,560003,No,Positive
23,Male,Single,Student,No Income,Post Graduate,2,13.0019,77.5713,560003,Yes,Positive
19,Male,Single,Student,No Income,Graduate,2,13.0019,77.5713,560003,No,Negative
19,Female,Single,Student,No Income,Graduate,4,12.9537,77.6176,560047,Yes,Positive
27,Female,Married,Employee,25001 to 50000,Post Graduate,2,12.9698,77.75,560066,No,Positive
25,Male,Single,Self Employeed,25001 to 50000,Graduate,3,12.998,77.6227,560005,Yes,Positive
33,Male,Married,Employee,More than 50000,Ph.D,5,12.998,77.6227,560005,No,Negative
26,Female,Single,Employee,More than 50000,Graduate,3,12.998,77.6227,560005,Yes,Positive
22,Female,Single,Student,Below Rs.10000,Post Graduate,4,12.9343,77.6044,560029,Yes,Positive
23,Male,Single,Student,No Income,Post Graduate,3,13.102,77.5864,560064,No,Positive
22,Female,Single,Student,No Income,Graduate,3,13.0158,77.539,560096,Yes,Negative
25,Male,Married,Employee,25001 to 50000,Graduate,2,12.998,77.6227,560005,Yes,Positive
30,Female,Married,House wife,No Income,School,5,12.998,77.6227,560005,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,3,13.0138,77.5877,560006,No,Negative
25,Male,Single,Employee,10001 to 25000,Post Graduate,3,13.0138,77.5877,560006,Yes,Positive
23,Male,Single,Student,More than 50000,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
24,Female,Single,Student,No Income,Post Graduate,4,13.0496,77.4941,560073,Yes,Positive
32,Male,Married,Employee,10001 to 25000,Graduate,4,12.9783,77.6408,560038,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,4,12.9889,77.5741,560020,Yes,Positive
23,Male,Single,Student,More than 50000,Post Graduate,3,12.977,77.5773,560009,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,13.0487,77.5923,560024,Yes,Positive
20,Male,Single,Student,No Income,Graduate,2,12.9579,77.6309,560007,Yes,Positive
21,Male,Single,Student,No Income,Graduate,2,12.9579,77.6309,560007,Yes,Positive
24,Female,Married,Self Employeed,10001 to 25000,Graduate,5,12.9579,77.6309,560007,Yes,Positive
23,Female,Single,Student,No Income,Post Graduate,4,13.0487,77.5923,560024,Yes,Positive
25,Male,Single,Employee,25001 to 50000,Post Graduate,3,12.985,77.5533,560010,Yes,Positive
32,Female,Married,House wife,No Income,Graduate,3,12.985,77.5533,560010,Yes,Positive
27,Male,Married,Employee,More than 50000,Ph.D,5,12.985,77.5533,560010,No,Negative
20,Female,Single,Student,No Income,Graduate,2,12.9337,77.59,560011,Yes,Positive
21,Male,Single,Student,No Income,Graduate,2,12.9337,77.59,560011,Yes,Positive
26,Male,Single,Employee,More than 50000,Post Graduate,3,12.9337,77.59,560011,No,Negative
25,Male,Single,Employee,10001 to 25000,Graduate,4,13.0166,77.6804,560016,Yes,Positive
26,Male,Single,Employee,25001 to 50000,Post Graduate,3,13.014,77.5658,560012,Yes,Positive
26,Female,Married,Employee,25001 to 50000,Graduate,3,13.014,77.5658,560012,Yes,Positive
27,Male,Single,Employee,More than 50000,Ph.D,4,13.0503,77.5529,560013,No,Positive
27,Female,Single,Student,No Income,Ph.D,5,13.0503,77.5529,560013,No,Negative
24,Female,Single,Student,No Income,Post Graduate,5,12.9883,77.5987,560051,Yes,Positive
25,Male,Married,Self Employeed,More than 50000,School,2,13.0626,77.5284,560015,Yes,Positive
20,Male,Single,Student,No Income,Graduate,2,13.0626,77.5284,560015,No,Negative
22,Male,Single,Student,No Income,Post Graduate,1,13.0626,77.5284,560015,Yes,Positive
26,Female,Married,Student,Below Rs.10000,Ph.D,3,13.0166,77.6804,560016,Yes,Positive
27,Male,Prefer not to say,Employee,25001 to 50000,Post Graduate,1,13.0166,77.6804,560016,Yes,Positive
25,Female,Single,Student,No Income,Post Graduate,3,12.9551,77.6593,560017,Yes,Positive
24,Male,Single,Employee,Below Rs.10000,Graduate,2,12.9551,77.6593,560017,Yes,Positive
23,Female,Single,Employee,10001 to 25000,Graduate,6,12.9551,77.6593,560017,Yes,Positive
22,Male,Single,Student,No Income,Graduate,2,12.957,77.5637,560018,No,Positive
26,Male,Married,Self Employeed,More than 50000,Post Graduate,3,12.957,77.5637,560018,No,Negative
26,Male,Single,Employee,Below Rs.10000,Post Graduate,1,12.957,77.5637,560018,Yes,Negative
25,Female,Married,Self Employeed,25001 to 50000,Post Graduate,3,12.957,77.5637,560018,No,Positive
29,Female,Married,Employee,More than 50000,Graduate,3,12.957,77.5637,560018,No,Positive
23,Male,Single,Student,Below Rs.10000,Graduate,3,12.8652,77.524,560109,Yes,Negative
22,Female,Single,Employee,25001 to 50000,Graduate,4,12.9698,77.75,560066,Yes,Positive
22,Male,Single,Student,No Income,Graduate,2,12.9889,77.5741,560020,No,Positive
32,Female,Married,House wife,No Income,School,5,12.9889,77.5741,560020,Yes,Positive
28,Male,Married,Employee,More than 50000,Post Graduate,1,12.9925,77.5633,560021,Yes,Positive
22,Male,Single,Student,No Income,Post Graduate,2,12.977,77.5773,560009,Yes,Positive
25,Male,Single,Employee,10001 to 25000,Graduate,2,12.9757,77.5586,560023,Yes,Positive
26,Female,Married,Employee,25001 to 50000,Post Graduate,2,12.9757,77.5586,560023,No,Negative
31,Male,Married,Self Employeed,More than 50000,School,6,13.0487,77.5923,560024,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,3,13.0487,77.5923,560024,No,Negative
24,Male,Single,Employee,25001 to 50000,Post Graduate,2,12.9662,77.6068,560025,Yes,Positive
31,Female,Married,Employee,More than 50000,Ph.D,5,12.9662,77.6068,560025,Yes,Positive
26,Male,Single,Employee,25001 to 50000,Graduate,2,12.9343,77.6044,560029,Yes,Positive
24,Female,Married,Self Employeed,More than 50000,Graduate,2,12.9343,77.6044,560029,Yes,Positive
22,Female,Single,Student,No Income,Graduate,3,12.9343,77.6044,560029,Yes,Positive
19,Male,Single,Student,No Income,Graduate,6,12.9442,77.6076,560030,Yes,Positive
25,Male,Married,Employee,More than 50000,Post Graduate,6,12.9442,77.6076,560030,Yes,Positive
23,Female,Married,House wife,No Income,School,6,12.9442,77.6076,560030,Yes,Positive
23,Female,Single,Student,No Income,Graduate,2,13.0298,77.6047,560032,No,Negative
23,Male,Single,Student,No Income,Post Graduate,2,12.9261,77.6221,560034,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,5,12.9621,77.5376,560104,Yes,Positive
22,Female,Single,Employee,25001 to 50000,Graduate,4,12.8845,77.6036,560076,Yes,Positive
26,Male,Married,Employee,More than 50000,Graduate,4,12.9048,77.6821,560036,Yes,Positive
25,Female,Single,Student,No Income,Ph.D,3,12.9048,77.6821,560036,Yes,Positive
20,Male,Single,Student,No Income,Graduate,2,12.9261,77.6221,560034,Yes,Positive
29,Male,Married,Employee,25001 to 50000,Graduate,4,12.9261,77.6221,560034,No,Negative
23,Female,Single,Student,No Income,Graduate,1,12.977,77.5773,560009,Yes,Positive
25,Male,Single,Self Employeed,More than 50000,Graduate,2,12.9783,77.6408,560038,Yes,Positive
29,Female,Married,Employee,25001 to 50000,Graduate,4,12.9783,77.6408,560038,No,Negative
27,Male,Married,Self Employeed,25001 to 50000,Graduate,6,12.9217,77.5936,560041,No,Negative
25,Male,Single,Self Employeed,10001 to 25000,Graduate,3,13.0206,77.6479,560043,Yes,Positive
21,Male,Single,Student,No Income,Graduate,2,13.0012,77.5995,560046,No,Negative
23,Male,Single,Student,No Income,Graduate,3,13.0223,77.7132,560049,Yes,Positive
24,Female,Single,Employee,10001 to 25000,Post Graduate,4,12.9337,77.59,560011,Yes,Positive
32,Male,Married,Self Employeed,10001 to 25000,School,3,12.982,77.6256,560008,Yes,Negative
28,Male,Married,Employee,25001 to 50000,Post Graduate,5,13.0262,77.62,560045,Yes,Positive
26,Male,Single,Employee,10001 to 25000,Graduate,2,12.9217,77.5936,560041,No,Negative
31,Female,Married,House wife,No Income,Graduate,5,13.0078,77.5577,560055,Yes,Positive
27,Female,Married,Self Employeed,25001 to 50000,Graduate,3,13.0078,77.5577,560055,Yes,Positive
21,Female,Single,Student,No Income,Post Graduate,1,12.9217,77.5936,560041,Yes,Positive
23,Female,Single,Student,No Income,Graduate,2,12.9105,77.4842,560060,No,Positive
26,Male,Married,Employee,10001 to 25000,Graduate,4,12.9105,77.4842,560060,No,Positive
32,Male,Married,Employee,More than 50000,Graduate,5,12.9037,77.5376,560061,Yes,Positive
25,Female,Married,Student,No Income,Post Graduate,2,12.8834,77.5486,560062,Yes,Positive
28,Male,Single,Self Employeed,10001 to 25000,Post Graduate,2,12.9149,77.5635,560070,Yes,Positive
21,Female,Single,Student,No Income,Post Graduate,3,12.9149,77.5635,560070,Yes,Positive
24,Male,Single,Student,No Income,Post Graduate,2,12.9706,77.6529,560075,Yes,Positive
26,Female,Married,Self Employeed,10001 to 25000,Graduate,5,12.9706,77.6529,560075,No,Negative

In [0]:
spark

In [0]:
people_data = spark.read.option('multiline', False)\
    .json('/FileStore/shared_uploads/ahmad/people.json')

In [0]:
display(people_data.filter(people_data.age >= 30))

age,city,name
30,NewYork,Jhon
34,Chicago,James

In [0]:
food_data = spark.read.option('multiline', True)\
    .option("mode", "PERMISSIVE")\
    .json('/FileStore/shared_uploads/ahmad/food.json')

In [0]:
display(food_data)

batters,id,name,ppu,topping,type
"List(List(List(1001, Regular), List(1002, Chocolate), List(1003, Blueberry), List(1004, Devil's Food)))",0001,Cake,0.55,"List(List(5001, None), List(5002, Glazed), List(5005, Sugar), List(5007, Powdered Sugar), List(5006, Chocolate with Sprinkles), List(5003, Chocolate), List(5004, Maple))",donut
"List(List(List(1001, Regular)))",0002,Raised,0.55,"List(List(5001, None), List(5002, Glazed), List(5005, Sugar), List(5003, Chocolate), List(5004, Maple))",donut
"List(List(List(1001, Regular), List(1002, Chocolate)))",0003,Old Fashioned,0.55,"List(List(5001, None), List(5002, Glazed), List(5003, Chocolate), List(5004, Maple))",donut

In [0]:
display(food_data.select('batters', 'name', 'id'))

batters,name,id
"List(List(List(1001, Regular), List(1002, Chocolate), List(1003, Blueberry), List(1004, Devil's Food)))",Cake,0001
"List(List(List(1001, Regular)))",Raised,0002
"List(List(List(1001, Regular), List(1002, Chocolate)))",Old Fashioned,0003

In [0]:
display(food_data.select('batters.batter.type', 'name', 'id'))

type,name,id
"List(Regular, Chocolate, Blueberry, Devil's Food)",Cake,0001
List(Regular),Raised,0002
"List(Regular, Chocolate)",Old Fashioned,0003

In [0]:
from pyspark.sql import functions as F

In [0]:
display(food_data.select(F.col('batters.batter.type')
                            .getItem(0)
                            .alias('batter_type')))

batter_type
Regular
Regular
Regular